### PR TITLE
Fix RemoveSpectator after making holes in array

### LINKED ISSUE #231: Compile-time error in removing the second spectator
```
S x;
CreateSpectator S,"S.spec";
CreateSpectator T,"T.spec";
L F = (1+x)^2;
if (count(x,1) == 1) tospectator S;
if (count(x,1) == 2) tospectator T;
.sort
CopySpectator SS = S;
CopySpectator TT = T;
P;
.sort
RemoveSpectator S;
RemoveSpectator T;  * <-- Error
.end
```
gives an error:
```
FORM 4.2.0 (Jul 16 2017, v4.2.0-16-g480a787) 64-bits  Run: Mon Sep 18 16:01:27 2017

   F =
      1;

   SS =
      2*x;

   TT =
      x^2;

    RemoveSpectator S;
    RemoveSpectator T;  *
Program terminating at test.frm Line 13 --> 
```
Valgrind output:
```
    RemoveSpectator S;
==27686== Invalid read of size 1
==27686==    at 0x4FE7B2: StrCmp (tools.c:1624)
==27686==    by 0x4E4A7E: CoRemoveSpectator (spectator.c:255)
==27686==    by 0x4260EF: CompileStatement (compiler.c:634)
==27686==    by 0x4AFE63: PreProcessor (pre.c:1045)
==27686==    by 0x4E87E0: main (startup.c:1605)
==27686==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==27686== 
    RemoveSpectator T;  *
Program terminating at test.frm Line 13 --> 
==27686== Invalid read of size 4
==27686==    at 0x502408: Crash (tools.c:3705)
==27686==    by 0x4E7F7C: Terminate (startup.c:1707)
==27686==    by 0x4E8684: onErrSig (startup.c:1476)
==27686==    by 0x5B6B74F: ??? (in /localstore/theorie/tueda/build/linuxbrew/Cellar/glibc/2.20/lib/libc-2.20.so)
==27686==    by 0x4FE7B1: StrCmp (tools.c:1624)
==27686==    by 0x4E4A7E: CoRemoveSpectator (spectator.c:255)
==27686==    by 0x4260EF: CompileStatement (compiler.c:634)
==27686==    by 0x4AFE63: PreProcessor (pre.c:1045)
==27686==    by 0x4E87E0: main (startup.c:1605)
==27686==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

### PR DESCRIPTION
**Pull request by jodavies**
Check that spectator names are not null pointers, before comparing.

RemoveSpectator leaves a hole in the SpectatorFiles array. One could fix this by moving all higher spectators to fill the hole, but creating new spectators later will at least fill the holes, currently.

Closes #231

### CODE REVIEW

File: sources/spectator.c [hunk 1]
```diff
@@ -252,7 +252,11 @@ int CoRemoveSpectator(UBYTE *inp)
 		return(1);
 	}
 	for ( i = 0; i < AM.SizeForSpectatorFiles; i++ ) {
-		if ( StrCmp((UBYTE *)(AM.SpectatorFiles[i].name),(UBYTE *)(inp)) == 0 ) break;
+		if (AM.SpectatorFiles[i].name != 0) {
```
Comment (tueda) [inline sources/spectator.c:255]: Can you follow Jos's coding style? (spaces inside the parentheses)

**Comment by tueda** [comment]
Thanks!
